Create board with tiled map
Foacs/ribz pull request #3
Opened 2020-09-16 20:37 UTC by dederobert

- Create screen management utility classes 
- Create board screen to render tiled map

2020-09-17 18:00 UTC, Vulture68 commented on core/src/main/java/fr/foacs/boardgame/core/BoardGame.java
> +  private BoardGame() {
Please add javadoc

2020-09-17 18:01 UTC, Vulture68 commented on core/src/main/java/fr/foacs/boardgame/core/BoardGame.java
> +   * Gets an instance of BoardGame.
Please use third person in the javadoc

2020-09-17 18:03 UTC, Vulture68 commented on core/src/main/java/fr/foacs/boardgame/core/BoardGame.java
> +    if (Objects.nonNull(splashScreenWorker)) {
👍

2020-09-17 18:05 UTC, Vulture68 commented on core/src/main/java/fr/foacs/boardgame/core/BoardGame.java
> +  public void showScreen(BoardGameScreens screen) {
Please use final identifier

2020-09-17 18:06 UTC, Vulture68 commented on core/src/main/java/fr/foacs/boardgame/core/controllers/BoardGameController.java
> +public interface BoardGameController {
Please use Get instead of Provide

2020-09-17 18:07 UTC, Vulture68 commented on core/src/main/java/fr/foacs/boardgame/core/models/Board.java
> +public class Board {
If all the fields have getters, you can annotate the class with @Getter

2020-09-17 18:08 UTC, Vulture68 commented on core/src/main/java/fr/foacs/boardgame/core/screens/AbstractScreen.java
> +public abstract class AbstractScreen extends ScreenAdapter {
@Getter

2020-09-17 18:08 UTC, Vulture68 commented on core/src/main/java/fr/foacs/boardgame/core/screens/AbstractScreen.java
> +  protected boolean rendered = false;
You forgot to put it private

2020-09-17 18:09 UTC, Vulture68 commented on core/src/main/java/fr/foacs/boardgame/core/screens/BoardGameScreens.java
> +  BoardGameScreens(BiFunction<BoardGameController, SpriteBatch, Screen> supplier) {
Please add javadoc

2020-09-17 18:10 UTC, Vulture68 commented on core/src/main/java/fr/foacs/boardgame/core/screens/BoardScreen.java
> +  public void setMapRenderer(OrthogonalTiledMapRenderer mapRenderer) {
Use Lombok#Setter annotation

2020-09-17 18:16 UTC, Vulture68 commented on core/src/test/java/fr/foacs/boardgame/core/BoardGameTest.java
> +class BoardGameTest {
Please add javadoc, also what do you think about using @DisplayName?

2020-09-17 18:19 UTC, Vulture68 commented on core/src/test/java/fr/foacs/boardgame/core/screens/BoardGameScreenTest.java
> +    when(controller.getAssetManager()).thenReturn(mock(AssetManager.class));
Please use Mockito#verify to check that your mocked method has been called

2020-09-17 18:20 UTC, Vulture68 commented on core/src/test/java/fr/foacs/boardgame/core/BoardGameTest.java
> +    verify(SPLASH_SCREEN_WORKER, times(1)).closeSplashScreen();
No need to specify "times(1)", the default implementation of verify(Mock) is to check times(1)

2020-09-17 18:21 UTC, Vulture68 commented on core/src/test/java/fr/foacs/boardgame/core/screens/BoardScreenTest.java
> +    Awaitility.await().atMost(2, TimeUnit.SECONDS).until(spyBoardScreen::isRendered);
LOL

2020-09-17 18:22 UTC, Vulture68 commented on core/src/test/java/fr/foacs/boardgame/core/screens/MockAssetManager.java
> +public class MockAssetManager extends AssetManager {
Please rename it AssetManagerMock, pleeeeeeeeeeeeeeeease 😢

2020-09-17 18:31 UTC, Vulture68 commented on desktop/build.gradle
> +//project.ext.assetsDir = new File("../core/src/resources")
Please remove

2020-09-17 18:33 UTC, Vulture68 commented on desktop/src/main/java/fr/foacs/boardgame/desktop/DesktopLauncher.java
>  public class DesktopLauncher {
Please add javadoc, and please set the args argument final

2020-09-17 18:34 UTC, Vulture68 commented on desktop/src/main/java/fr/foacs/boardgame/desktop/DesktopSplashScreenWorker.java
> +import java.awt.*;
Please remove *

2020-09-17 18:34 UTC, Vulture68 requested changes
Please take care of the comments

2020-09-19 11:26 UTC, Vulture68 requested changes
Please review the comments

2020-09-19 11:26 UTC, Vulture68 commented on .idea/codeStyles/Project.xml
> +      <option name="PACKAGES_TO_USE_IMPORT_ON_DEMAND">
Why is the value tag alone? Why doesn't it have friends? Is it needed?

2020-09-19 11:26 UTC, Vulture68 commented on core/src/main/java/fr/foacs/ribz/core/BoardGame.java
> +  private static final BoardGame instance = new BoardGame();
Why don't you use the ENUM way to manage the singleton here?

2020-09-19 11:26 UTC, Vulture68 commented on core/src/test/java/fr/foacs/ribz/core/mocks/OrthographicCameraMock.java
> +    // Avoid calling parent constructor
What? Then why is it public? Is it imposed by the API?

2020-09-19 11:26 UTC, Vulture68 commented on core/src/test/java/fr/foacs/ribz/core/utils/PropertiesLoaderTest.java
> +        e.printStackTrace();
Please avoid the "catch(e) { e.printStackTrace(); }". Consider using the Lombok#SneakyThrows annotation instead.

2020-09-19 11:30 UTC, dederobert commented on core/src/main/java/fr/foacs/ribz/core/BoardGame.java
> +  private static final BoardGame instance = new BoardGame();
It's not possible to create enum which extends a class. In this case `Game`

2020-09-19 11:32 UTC, dederobert commented on core/src/test/java/fr/foacs/ribz/core/mocks/OrthographicCameraMock.java
> +    // Avoid calling parent constructor
This is a mock, it's main purpose is to avoid calling framework graphics method which failed during test.
This constructor hide the default one which will call the parent's constructor and call graphics methods.

2020-09-19 11:35 UTC, Vulture68 commented on core/src/test/java/fr/foacs/ribz/core/mocks/OrthographicCameraMock.java
> +    // Avoid calling parent constructor
Oh... OK then

2020-09-19 11:36 UTC, Vulture68 commented on core/src/main/java/fr/foacs/ribz/core/BoardGame.java
> +  private static final BoardGame instance = new BoardGame();
Oh... OK then

2020-09-19 11:37 UTC, dederobert commented on .idea/codeStyles/Project.xml
> +      <option name="PACKAGES_TO_USE_IMPORT_ON_DEMAND">
This line specified to Intellij which package it can import with a wildcard. By default it's set to `java.awt` and `java.swing`.
The empty tag specify explicitly we want no package imported by using wildcard.

2020-09-19 12:36 UTC, Vulture68 commented on .idea/codeStyles/Project.xml
> +      <option name="PACKAGES_TO_USE_IMPORT_ON_DEMAND">
Oh... OK then

2020-09-19 12:38 UTC, Vulture68 approved these changes
GG well play 👍

2020-09-19 12:39 UTC, merged

2020-09-19 12:41 UTC, Vulture68 commented
For info, I won't delete a branch after a merge UNLESS you explicitly ask me to, be it with a comment in the PR or directly in its description. Even if a branch deletion can be reverted, I'm not responsible for it, so I don't want to take the decision myself.